project:
  type: website

website:
  title: "Aritra · Quarto"
  site-url: "https://techie5879.github.io/quarto4"
  site-path: "/quarto4/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publication/index.qmd
        text: Publications
      - href: experience/index.qmd
        text: Experience
      - href: blog/index.qmd
        text: Blog
    right:
      - text: CV
        href: /media/resume.pdf

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: false
    page-layout: article
