title: "Aritra · Jekyll"
description: "Jekyll preview inspired by the academic al-folio ecosystem."
url: "https://techie5879.github.io"
baseurl: "/jekyll1"
markdown: kramdown
permalink: pretty

collections:
  blog_posts:
    output: true
    permalink: /blog/:name/
  publications:
    output: true
    permalink: /publication/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
